title: Your Blog Title
description: A single-page blog about your interests.
theme: minima  # Use a free theme like "minima"
url: "https://yourblogurl.com"  # Replace with your actual URL
baseurl: ""  # Leave empty if your site is at the root
author:
  name: Your Name
  email: your.email@example.com