title: TRooTech Blog
description: A single-page blog about your interests.
theme: jekyll-theme-minimal  # Use a free theme like "minima"
url: "https://trootech-knowledgebase.com"  # Replace with your actual URL
baseurl: ""  # Leave empty if your site is at the root
author:
  name: Vishal Nakum
  email: vishal.nakum@trootech.com